name: Build Dictionary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install jq
      run: sudo apt-get install jq

    - name: Combine JSON files
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          const outputPath = 'dictionary.json';
          const localsDir = 'locals';

          let dictionary = {};

          fs.readdirSync(localsDir).forEach(file => {
            if (path.extname(file) === '.json') {
              const lang = path.basename(file, '.json');
              const filePath = path.join(localsDir, file);
              try {
                const fileContent = JSON.parse(fs.readFileSync(filePath, 'utf8'));
                dictionary[lang] = fileContent;
              } catch (error) {
                console.log(`Skipping invalid JSON file: ${file}`);
              }
            }
          });

          fs.writeFileSync(outputPath, JSON.stringify(dictionary, null, 2));
          
          console.log('dictionary.json has been updated');

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add dictionary.json
        git commit -m 'Update dictionary.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
